# Generated by Django 5.2.7 on 2025-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game_setting',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
