# Generated by Django 5.2.7 on 2025-10-04 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_system_event_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
